export const TEXTS: string[] = [
  " likes programming",
  " likes algorithms",
  " likes create custom charts",
  " likes making custom charts",
  " likes rxjs",
  " likes geometry",
  " likes math",
  " likes engineering",
  " plays the violin",
  " ready to help",
  " is a frontend developer",
  " has a diploma from NTUU KPI",
  " practise shader programming here",
  " lives in Kyiv",
  " love his wife",
];
